name: Go

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26"]
    name: Build Go ${{ matrix.go-version == '1.26' && '(latest)' || '(old)' }}
    defaults:
      run:
        working-directory: ./gomuks

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libolm-dev libolm3 libgtk-3-dev libwebkit2gtk-4.1-dev libsoup-3.0-dev

      - name: Create web stub
        run: |
          mkdir -p web/dist
          touch web/dist/empty

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
